name: A workflow for my Hello World docker
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Run command
        run: |
          docker run -it hello-world
